Iss983 - Set handled flag on mouse released
nion-software/nionui pull request #77
Opened 2024-07-30 11:17 UTC by Tiomat85

When a mouse-released event is handled,  set the accepted flag on the event so it doesn't propagate up to the parent control and trigger a selection event.

2024-07-30 12:49 UTC, cmeyer commented
Is this fixing a bug? If so, can you reference the issue or file an issue describing the problem? This looks like a valid change to fix the problem of multiple fields being highlighted at once...?

2024-07-30 12:55 UTC, cmeyer commented on nion/ui/QtUserInterface.py
> +            return  self.on_mouse_released(x, y, QtKeyboardModifiers(raw_modifiers))
Two comments here: (a) minor white space issue (should be one space after return); (b) no return statement for the 'else' fall through.

2024-07-30 12:58 UTC, Tiomat85 commented on nion/ui/QtUserInterface.py
> +            return  self.on_mouse_released(x, y, QtKeyboardModifiers(raw_modifiers))
It is fixing Issue 983: https://github.com/nion-software/nionswift/issues/983

Fixed those two minor issues.

2024-07-30 12:59 UTC, Tiomat85 commented on nion/ui/QtUserInterface.py
> +            return  self.on_mouse_released(x, y, QtKeyboardModifiers(raw_modifiers))
There may have been other UI issues caused by it, or the similar behaviour with mouse pressed or clicked causing double effects.

2024-07-30 13:55 UTC, cmeyer commented on nion/ui/QtUserInterface.py
> +            return self.on_mouse_released(x, y, QtKeyboardModifiers(raw_modifiers)
You probably saw this already, but this line is missing a closing parenthesis.

2024-07-30 14:00 UTC, Tiomat85 commented on nion/ui/QtUserInterface.py
> +            return self.on_mouse_released(x, y, QtKeyboardModifiers(raw_modifiers)
I had when trying to work on the next task wasn't working, and was busy squashing commits while the kettle was boiling, but thanks for highlighting it anyway in case I had missed it.

2024-08-07 23:45 UTC, cmeyer requested changes
`nionui` should not know about `nionswift` - so needs some work here.

2024-08-07 23:45 UTC, cmeyer commented on nion/ui/CanvasItem.py
> +                selection_mode = False
This is a significant break of encapsulation and needs to be rewritten in a different way. It is accessing a special case in the `nionswift` project of the `tool_mode` being set to `pointer`. `nionui` intentionally does not know about anything in `nionswift`, as it is a lower level library.

Generally the mouse tracking code is difficult to understand, but can you explain what you're doing here and then we can come up with a solution?

Does the mouse canvas item need something like "handles first clicks"? Something like this https://developer.apple.com/documentation/appkit/nsview/1483410-acceptsfirstmouse

2024-08-09 12:41 UTC, Tiomat85 commented on nion/ui/CanvasItem.py
> +                selection_mode = False
So this was to effectively differentiate between the software (cursor specifically) being in 'selection' mode rather than any other mode such as graphic drawing etc.  What I found was that the handlers for the events were not always returning a value indicating successful handling of the event.  So specifically the MouseHandler mouse_released function just passes the event on but it has no idea if that event is then being handled by whatever is looping and reading those events.
Since that feedback isn't available at that point of whether or not the event was handled, the event was being re-triggered and handled twice (the drawing of the graphic, and the selection) unless there is a way to identify whether the software is currently in a 'selecting' mode or not.  

That is the bit that is needed here, that the ui layer is in a selection mode and it was a relatively simple way that I got to work pretty easily.  If there is something else already in nionui that has that information please point me towards it and I can refactor it to that.

2024-08-09 17:17 UTC, cmeyer commented on nion/ui/CanvasItem.py
> +                selection_mode = False
I think the only way to go forward is to have the panel in Swift make the decisions and return the correct result. I can't think of a super-clean solution, but, based on your ideas, here is a Swift-only solution:

https://github.com/nion-software/nionswift/pull/1130

2024-08-14 14:55 UTC, cmeyer commented
Closing in favor of the solution here https://github.com/nion-software/nionswift/pull/1130

See notes here, too https://github.com/nion-software/nionui-tool/pull/63

2024-08-14 14:55 UTC, closed without merging